### ISSUE TITLE
Local data source

### ISSUE THREAD

**Issue by l4u** [mapbox/mapbox-studio-osm-bright.tm2#15]
May I know if the local data source in SQL queries from osm-bright (osm-bright.osm2pgsql.mml) will be ported to osm-bright.tm2 or not?

**Comment by tsauerwein** [comment]
If someone else is also interested in this: I started working on a MapBox Studio source for this style, that can be used with local OSM data. It is still incomplete, but it's a start. :)

https://github.com/osm-for-schools/osm-bright.tm2source
