### ISSUE TITLE
Secondary roads not styled

### ISSUE THREAD

**Issue by revenger73** [mapbox/mapbox-studio-osm-bright.tm2#23]
OSM-Bright is not styling secondary roads (In dutch N-roads) with new planet.mbtile from osm2vectortiles.org

![osm-bright-n-roads-no-style](https://cloud.githubusercontent.com/assets/5694333/15575015/f90a27ba-2350-11e6-97e1-8998844a74b9.png)

**Comment by ajashton** [comment]
Hi, it looks like tiles from osm2vectortiles are made to be [compatible with Mapbox Streets v7](https://github.com/osm2vectortiles/osm2vectortiles/tree/master/osm2vectortiles.tm2source), but this project is designed against [Mapbox Streets v6](https://www.mapbox.com/vector-tiles/mapbox-streets-v6/). We have no plans to upgrade this style to v7, so you can either do this yourself or use this style with Mapbox Streets v6 vector tiles.

**Comment by revenger73** [comment]
Hey! 

If you were looking for something really fantastic and cool, than  you found  it! Just take a look   <http://full.yadlin.org/e4uiud>

Best Wishes, revenger

**Comment by revenger73** [comment]
Hey, 


I just wanted  to share something really  exciting, just take  a look <http://world.smokedetectors.us/e4iwqhmy>


Faithfully, revenger

**Comment by revenger73** [comment]
Greetings, 

I've had  a nice  day today and wanted to share  this with you,  check it  out <http://nkopetifra.danielbarsky.com/e4uwdxw>

Best wishes, revenger
