### ISSUE TITLE
How can I use it with mapnik and mod_tile

### ISSUE THREAD

**Issue by CrazyCoder4Carrot** [mapbox/mapbox-studio-osm-bright.tm2#27]
I've download the project to the dick and change the configuration file in the /usr/local/etc/renderd.conf. But the result is gray pic.

**Comment by ajashton** [comment]
> How can I use it with mapnik and mod_tile

The short answer is you can't, at least not directly. This style is designed to be uploaded to a Mapbox.com account using Mapbox Studio Classic. You can use the icons and modified versions of the CartoCSS in your own custom style with custom data sources, but there's quite a lot of work involved in that. As-is this repository relies on Mapbox-hosted vector tiles to work.
